In [1]:
import pandas as pd

main_df = pd.read_csv(r'C:\Users\akozhevnikov\Downloads\hakatone\bsm_data_train.csv')
main_df = main_df.drop_duplicates('ident_bag', keep='first').reset_index(drop=True)
main_df

,ident_bag,i_id,pax_id_hash,MessageReceivedDate,MessageProcessedDate,DateEvent,TagNumber,local_or_transfer
0,62562416,8628981.0,dcd856b334b9685c4f21afa67f3ddc70,2023-07-01 06:53:34.413,2023-07-01 06:53:37.720,2023-07-01 06:53:37.717,2425399448,L
1,62571791,8628981.0,dcd856b334b9685c4f21afa67f3ddc70,2023-07-01 06:53:24.603,2023-07-01 06:53:28.590,2023-07-01 06:53:28.577,2425388102,L
2,62553945,8629051.0,f2b931876cac089c6a02af1b70d08c61,2023-07-01 06:59:56.263,2023-07-01 06:59:59.610,2023-07-01 06:59:59.607,3555170959,L
3,62574680,8629296.0,2e3291401628ca69061c49b3319793a1,2023-07-01 14:34:52.870,2023-07-01 14:34:55.547,2023-07-01 14:34:55.543,2316437470,L
4,62575458,8629296.0,2e3291401628ca69061c49b3319793a1,2023-07-01 14:34:35.300,2023-07-01 14:34:39.380,2023-07-01 14:34:39.380,2316437464,L
...,...,...,...,...,...,...,...,...
1989371,64616153,8687750.0,1724dd3d56108fea2c917f370f77e664,2023-08-31 23:59:50.757,2023-08-31 23:59:53.393,2023-08-31 23:59:53.390,263789487,L
1989372,64616152,8687783.0,45ca01ef5df1fda1da6b9a85e0a26628,2023-08-31 23:59:50.757,2023-08-31 23:59:53.370,2023-08-31 23:59:53.367,395191461,L
1989373,64616154,8687786.0,2acb4b86315d6e49efc0a824b3cba80d,2023-08-31 23:59:53.600,2023-08-31 23:59:57.260,2023-08-31 23:59:57.257,7115420782,L
1989374,64616155,8687774.0,1d767047c6955c86ef4e0626bc60d213,2023-08-31 23:59:55.637,2023-08-31 23:59:57.413,2023-08-31 23:59:57.413,216561658,L
1989375,64616156,8688045.0,e00a871c3291782beb9de879fa5bcf71,2023-08-31 23:59:56.857,2023-08-31 23:59:57.547,2023-08-31 23:59:57.543,555105787,T

In [2]:
main_df['MessageReceivedSeconds'] = pd.to_datetime(main_df['MessageReceivedDate']).apply(lambda x: x.value) / 1000000000
main_df['MessageReceivedSeconds'] -= main_df['MessageReceivedSeconds'].min()
main_df['MessageReceivedSeconds'] = (main_df['MessageReceivedSeconds'] // 60).astype(int)
main_df = main_df.sort_values(by='MessageReceivedSeconds')
main_df

,ident_bag,i_id,pax_id_hash,MessageReceivedDate,MessageProcessedDate,DateEvent,TagNumber,local_or_transfer,MessageReceivedSeconds
24,62582289,8628896.0,fd9df7b143e63e79d5260fc21ca97db6,2023-07-01 00:01:01.843,2023-07-01 00:01:05.583,2023-07-01 00:01:05.580,555966473,L,0
26,62582291,8628888.0,e8caeb9273f8eb7ef74a1ca81e7d7e0d,2023-07-01 00:01:03.883,2023-07-01 00:01:06.037,2023-07-01 00:01:06.033,555051923,L,0
25,62582290,8628883.0,8fe4990b9753001ee8e3217ed529d17f,2023-07-01 00:01:02.663,2023-07-01 00:01:05.857,2023-07-01 00:01:05.853,555046631,L,0
23,62582288,8629186.0,963fd5c737cb22da29b31ea0eac85fb8,2023-07-01 00:01:00.623,2023-07-01 00:01:05.410,2023-07-01 00:01:05.407,555944815,T,0
22,62582287,8628902.0,c54120fd0cde2d55a70b6383af34381d,2023-07-01 00:00:48.627,2023-07-01 00:00:51.130,2023-07-01 00:00:51.127,555007658,L,0
...,...,...,...,...,...,...,...,...,...
1989350,64616131,8687838.0,8479e2b93d72cbd4399fa31de84013e3,2023-08-31 23:59:10.413,2023-08-31 23:59:13.033,2023-08-31 23:59:13.030,555475009,T,89279
1989349,64616130,8688009.0,8a8a644086752ab32e056550927b7996,2023-08-31 23:59:05.537,2023-08-31 23:59:08.983,2023-08-31 23:59:08.980,555256544,T,89279
1989374,64616155,8687774.0,1d767047c6955c86ef4e0626bc60d213,2023-08-31 23:59:55.637,2023-08-31 23:59:57.413,2023-08-31 23:59:57.413,216561658,L,89279
1989361,64616142,8687766.0,914af60b3dc9f64926b735d85189afca,2023-08-31 23:59:25.483,2023-08-31 23:59:29.097,2023-08-31 23:59:29.093,555439285,L,89279
1989375,64616156,8688045.0,e00a871c3291782beb9de879fa5bcf71,2023-08-31 23:59:56.857,2023-08-31 23:59:57.547,2023-08-31 23:59:57.543,555105787,T,89279

In [3]:
main_df['Recived_Processed'] = (pd.to_datetime(main_df['MessageProcessedDate']) - pd.to_datetime(main_df['MessageReceivedDate'])).apply(lambda x: x.seconds)

In [6]:
%%time
df = main_df[['MessageReceivedSeconds', 'Recived_Processed']].groupby('MessageReceivedSeconds').sum()

Wall time: 146 ms

In [7]:
df

                        Recived_Processed
MessageReceivedSeconds
0                                      42
1                                      55
2                                      32
3                                      58
4                                      38
...                                   ...
89275                                  51
89276                                  56
89277                                  66
89278                                  64
89279                                  40

[89217 rows x 1 columns]

In [5]:
def calculate_anomaly(new_values: pd.Series, # список значений новых
                      column_name: str, # какой признак, должен быть в stats
                      stats: dict, 
                      update_stats=True):
    result = (new_values - stats[column_name]['mean']) >  stats[column_name]['std']*3
    iqr = stats[column_name]['q75'] - stats[column_name]['q25']
    lower_bound = stats[column_name]['q25'] - 1.5 * iqr
    upper_bound = stats[column_name]['q75'] + 1.5 * iqr
    result += new_values > upper_bound
    if lower_bound > 0:
        result += new_values < lower_bound
    return result

In [8]:
# исторические базовые данные 
# TODO сделать чтобы они обновлялись 
stats = {'Recived_Processed': {'mean': df['Recived_Processed'].mean(), 
                               'count': len(df['Recived_Processed']),
                              'std': df['Recived_Processed'].std(),
                              'q25': df['Recived_Processed'].quantile(0.25),
                               'q50': df['Recived_Processed'].quantile(0.50),
                               'q75': df['Recived_Processed'].quantile(0.75)}}

In [9]:
new_values = pd.Series([38., 1000., 40., 35., 99.])

In [10]:
result = calculate_anomaly(new_values, 'Recived_Processed', stats)

C:\Users\akozhevnikov\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\computation\expressions.py:203: UserWarning: evaluating in Python space because the '+' operator is not supported by numexpr for the bool dtype, use '|' instead
  warnings.warn(

In [12]:
result

0    False
1     True
2    False
3    False
4     True
dtype: bool